version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:16
    hostname: dpg-cr1c183qf0us73flel0g-a
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=greetings_006i
      - POSTGRES_USER=greetings_006i_user
      - POSTGRES_PASSWORD=0w3KpbWU691HEOZRxqaOb5l6Ypv92ssY
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  webapi:
    build:
      dockerfile: Dockerfile
      context: .
    hostname: webapi
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-cr1c183qf0us73flel0g-a:5432/greetings_006i
      - SPRING_DATASOURCE_USERNAME=greetings_006i_user
      - SPRING_DATASOURCE_PASSWORD=0w3KpbWU691HEOZRxqaOb5l6Ypv92ssY
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 10s