version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:16
    hostname: dpg-cr1cmbrqf0us73fll1mg-a
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=greetings_8z8k
      - POSTGRES_USER=greetings_8z8k_user
      - POSTGRES_PASSWORD=8dscDoSEle05Gd2o4BSKOjXdQrmNI2NH
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  webapi:
    build:
      dockerfile: Dockerfile
      context: .
    hostname: webapi
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-cr1cmbrqf0us73fll1mg-a:5432/greetings_8z8k
      - SPRING_DATASOURCE_USERNAME=greetings_8z8k_user
      - SPRING_DATASOURCE_PASSWORD=8dscDoSEle05Gd2o4BSKOjXdQrmNI2NH
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 10s